# Generated by Django 5.2 on 2025-04-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('filiere', models.CharField(choices=[('informatique', 'Informatique'), ('reseaux', 'Réseaux et Télécommunications'), ('securite', 'Sécurité Informatique'), ('autre', 'Autre')], max_length=50)),
                ('cni', models.FileField(upload_to='documents/cni/')),
                ('diplome', models.FileField(upload_to='documents/diplomes/')),
                ('photo', models.ImageField(upload_to='documents/photos/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('code_inscription', models.CharField(blank=True, max_length=20, unique=True)),
            ],
        ),
    ]
